name: hugo-deploy

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  skip_check:
    continue-on-error: false
    runs-on: ubuntu-22.04
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
    - id: skip_check
      uses: fkirc/skip-duplicate-actions@v5
      with:
        concurrent_skipping: 'same_content'
        cancel_others: 'true'
        skip_after_successful_duplicate: 'true'
        paths: '["docs/**", ".github/workflows/hugo-deploy.yml"]'
        do_not_skip: '["workflow_dispatch", "schedule"]'

  build:
    needs: skip_check
    if: needs.skip_check.outputs.should_skip != 'true'
    runs-on: ubuntu-22.04
    env:
      HUGO_VERSION: 0.141.0

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup Pages
      id: pages
      uses: actions/configure-pages@v5

    - name: Install Hugo CLI
      run: wget -O ${{ runner.temp }}/hugo.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-amd64.deb && sudo dpkg -i ${{ runner.temp }}/hugo.deb
 
    - name: Build website
      working-directory: ./docs
      env:
        HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
        HUGO_ENVIRONMENT: production
      run: hugo --gc --minify --baseURL "${{ steps.pages.outputs.base_url }}/"

    - name: Deploy to gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ github.workspace }}/docs/public
